server:
  port: 8080
spring:
  application:
    name: seve-gateway
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: seve-auth
          uri: lb://seve-auth
          predicates:
            - Path=/seve-auth/**
          filters:
           - StripPrefix=1

          