server:
  port: 8081

spring:
  application:
    name: seve-auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/seve-auth?allowMultiQueries=true&autoReconnect=true&useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-flex:
  global-config:
    print-banner: false